### ISSUE TITLE
experiment with presistent storage plugin

### ISSUE THREAD

**Issue by bitboxer** [bitboxer/dotfiles#10]
https://github.com/kusnier/vagrant-persistent-storage

**Comment by moonglum** [comment]
Interesting solution 🤔

**Comment by bitboxer** [comment]
Lets see how good it works in practice. But currently I am highly confident that this is exactly what I needed. Persistent data, no slow down because of weird nfs behavior.

**Comment by moonglum** [comment]
I'm currently experimenting with [something else](https://github.com/moonglum/electric_monk). I'll keep you posted 😸
