### ISSUE TITLE
Move to vagrant

### ISSUE THREAD

**Issue by bitboxer** [bitboxer/dotfiles#2]
- [X] Check out old `packages.yml` and figure out what is needed
- [X] Remove stuff from host mac
- [x] Document this
- [x] Add list with apps I install on the mac
- [x] Figure out how to deal with code, NFS mount is not ideal
- [x] install [go](https://www.digitalocean.com/community/tutorials/how-to-install-go-1-6-on-ubuntu-16-04)
  - [x] [sush](https://github.com/realestate-com-au/shush)
  - [x] hub
- [x] git-crypt

**Comment by moonglum** [comment]
[This is how I install hub](https://github.com/moonglum/dotfiles/blob/master/ansible/playbook.yml#L151-L159). If you find a better way: Let me know 😄

**Comment by bitboxer** [comment]
I want to do `go get github.com/github/hub` and parameterise that so that I can also install other go based tools like `sush`.

**Comment by moonglum** [comment]
Oh! That makes sense 👍 I'll steal that when you're done 😊

**Comment by bitboxer** [comment]
@moonglum see here: https://github.com/bitboxer/dotfiles/commit/9ab2c431e498525834a1adb7df0380f2c96de921

**Comment by moonglum** [comment]
Thanks 🙇 Here is the commit containing some other improvements as well: https://github.com/moonglum/dotfiles/commit/b735a99363d65d9983d4bc6c46f0b9e147a71a33
